@extends('template.frontend.template')
@extends('template.frontend.home')
@extends('template.frontend.header')
@extends('template.frontend.rightsidebar')
@extends('template.frontend.bottombar')
@extends('template.frontend.footer')